version: "2"
run:
  timeout: 5m
linters:
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - unconvert
    - usestdlibvars
    - wastedassign
  settings:
    errcheck:
      exclude-functions:
        - fmt.Sscanf
    gocritic:
      disabled-checks:
        - ifElseChain
    gosec:
      excludes:
        - G107
        - G402
      severity: high
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
        text: G101
    paths:
      - portainer_data
      - e2e-tests
      - examples
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - portainer_data
      - e2e-tests
      - examples
      - third_party$
      - builtin$
      - examples$
