---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    # Get version (rev) from:
    # https://github.com/antonbabenko/pre-commit-terraform/releases
    rev: "v1.88.4"
    hooks:
      - id: terraform_t-fmt
      - id: terraform_t-docs
