package internal

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/go-openapi/runtime"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/portainer/client-api-go/v2/pkg/client/endpoints"
	"github.com/portainer/client-api-go/v2/pkg/models"
)

func resourceEnvironment() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceEnvironmentCreate,
		ReadContext:   resourceEnvironmentRead,
		DeleteContext: resourceEnvironmentDelete,
		UpdateContext: resourceEnvironmentUpdate,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Name of the Portainer environment (endpoint) as displayed in the UI.",
			},
			"environment_address": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Connection URL of the environment (e.g. tcp://host:port for Docker, https://host for Kubernetes/Agent). Used as the endpoint URL Portainer connects to.",
			},
			"public_ip": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Public IP/URL used by Portainer for Published Ports (maps to PublicURL).",
			},
			"type": {
				Type:        schema.TypeInt,
				Required:    true,
				Description: "Environment type: 1 = Docker, 2 = Agent, 3 = Azure, 4 = Edge Agent, 5 = Kubernetes, 6 = Kubernetes via agent, 7 = Kubernetes Edge Agent",
				ValidateFunc: func(val interface{}, key string) (warns []string, errs []error) {
					t := val.(int)
					if t < 1 || t > 7 {
						errs = append(errs, fmt.Errorf("%q must be between 1 and 7", key))
					}
					return
				},
				DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
					// Portainer converts Edge Agent type 4 to Kubernetes Edge Agent type 7
					// after agent connection. Suppress this expected drift.
					if old == "7" && new == "4" {
						return true
					}
					return false
				},
			},
			"group_id": {
				Type:        schema.TypeInt,
				Optional:    true,
				Default:     1,
				Description: "ID of the Portainer endpoint group. Default is 1 (Unassigned).",
			},
			"tag_ids": {
				Type:        schema.TypeList,
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeInt},
				Description: "List of tag IDs to assign to the environment.",
			},
			"tls_enabled": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     true,
				Description: "Whether TLS is enabled for the connection to the environment.",
			},
			"tls_skip_verify": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     true,
				Description: "Whether to skip server TLS certificate verification when connecting to the environment.",
			},
			"tls_ca_cert": {
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				Description: "PEM-encoded TLS CA certificate used to verify the environment's server certificate. Stored in state as a sensitive value.",
			},
			"tls_cert": {
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				Description: "PEM-encoded TLS client certificate presented by Portainer when connecting to the environment. Stored in state as a sensitive value.",
			},
			"tls_key": {
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				Description: "PEM-encoded TLS client private key paired with tls_cert. Stored in state as a sensitive value.",
			},
			"tls_skip_client_verify": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     true,
				Description: "Whether to skip client TLS certificate verification when Portainer connects to the environment.",
			},
			"edge_key": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Edge key generated by Portainer for type 4/7 (Edge Agent) environments. Used by the Edge Agent to register with Portainer.",
			},
			"edge_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Edge identifier (UUID) for type 4/7 (Edge Agent) environments, to pass to the Edge Agent as PORTAINER_EDGE_ID. Returned by Portainer when the EnforceEdgeID setting is enabled, otherwise generated by the provider at create time. Empty for all other environment types.",
			},
			"user_access_policies": {
				Type:     schema.TypeMap,
				Optional: true,
				Elem: &schema.Schema{
					Type: schema.TypeInt,
				},
				Description: "Map of user IDs to role IDs (e.g. userID -> roleID)",
			},
			"team_access_policies": {
				Type:     schema.TypeMap,
				Optional: true,
				Elem: &schema.Schema{
					Type: schema.TypeInt,
				},
				Description: "Map of team IDs to role IDs (e.g. teamID -> roleID)",
			},
		},
	}
}

// ensureEdgeID gives Edge Agent environments a usable edge_id when Portainer
// does not supply one. The server only assigns an Edge ID at creation while the
// EnforceEdgeID setting is enabled; otherwise the endpoint's EdgeID stays empty
// until an agent connects and reports one, leaving nothing to template
// PORTAINER_EDGE_ID from (issue #142). The Portainer UI covers the same gap by
// generating a UUID client-side for its deployment script, and the server adopts
// the ID the agent reports while its own is empty, so the generated value
// becomes the authoritative one.
//
// It must stay create-time only. Read carries an existing value forward from
// state, so minting one there would be stable on refresh — but a plan does not
// persist the state it refreshes, so a resource whose stored edge_id is empty
// (imported, or created by an earlier provider version) would mint a fresh UUID
// on every plan and show phantom drift to anything referencing it. Those cases
// stay empty until an agent associates; see docs/resources/environment.md.
//
// The type is read back from state (i.e. as reported by the API), because
// Portainer's creation enum stops at 5 and can hand back a non-edge environment
// for a type it does not recognise.
func ensureEdgeID(d *schema.ResourceData) error {
	envType := d.Get("type").(int)
	if envType != 4 && envType != 7 {
		return nil
	}
	if d.Get("edge_id").(string) != "" {
		return nil
	}
	return d.Set("edge_id", uuid.New().String())
}

func resourceEnvironmentCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*APIClient)
	name := d.Get("name").(string)

	if existingID, err := findExistingEnvironmentByName(client, name); err != nil {
		return diag.FromErr(fmt.Errorf("failed to check for existing environment: %w", err))
	} else if existingID != 0 {
		d.SetId(strconv.Itoa(existingID))
		if diags := resourceEnvironmentUpdate(ctx, d, meta); diags.HasError() {
			return diags
		}
		return diag.FromErr(ensureEdgeID(d))
	}

	envType := d.Get("type").(int)
	endpointCreationType := int64(envType)
	if envType == 6 {
		endpointCreationType = 2
	}

	params := endpoints.NewEndpointCreateParams()
	params.SetName(name)
	params.SetEndpointCreationType(endpointCreationType)

	// Edge Agent creation (type 4) is ambiguous on the Portainer side: without a
	// container engine hint Portainer provisions the endpoint as a Kubernetes
	// Edge Agent (type 7) instead of a Docker Edge Agent (type 4). Sending
	// ContainerEngine=docker pins it to the Docker edge type the user asked for
	// (issues #140 / #93). type 7 intentionally leaves it unset so Portainer
	// keeps the Kubernetes edge type.
	if envType == 4 {
		containerEngine := "docker"
		params.SetContainerEngine(&containerEngine)
	}

	url := strings.TrimSpace(d.Get("environment_address").(string))
	params.SetURL(&url)

	groupID := int64(d.Get("group_id").(int))
	params.SetGroupID(&groupID)

	if v, ok := d.GetOk("public_ip"); ok && v.(string) != "" {
		purl := v.(string)
		params.SetPublicURL(&purl)
	}

	// Edge Agent environments (type 4, 7) do not support TagIds in the
	// multipart Create request. Tags are applied via a follow-up Update call.
	isEdgeAgent := envType == 4 || envType == 7
	if v, ok := d.GetOk("tag_ids"); ok && !isEdgeAgent {
		tagIDs := []int64{}
		for _, id := range v.([]interface{}) {
			tagIDs = append(tagIDs, int64(id.(int)))
		}
		params.SetTagIds(tagIDs)
	}

	tlsEnabled := d.Get("tls_enabled").(bool)
	params.SetTLS(&tlsEnabled)
	tlsSkipVerify := d.Get("tls_skip_verify").(bool)
	params.SetTLSSkipVerify(&tlsSkipVerify)
	tlsSkipClientVerify := d.Get("tls_skip_client_verify").(bool)
	params.SetTLSSkipClientVerify(&tlsSkipClientVerify)

	if tlsEnabled && !tlsSkipVerify {
		if v, ok := d.GetOk("tls_ca_cert"); ok && v.(string) != "" {
			params.SetTLSCACertFile(runtime.NamedReader("ca.pem", strings.NewReader(v.(string))))
		}
		if v, ok := d.GetOk("tls_cert"); ok && v.(string) != "" {
			params.SetTLSCertFile(runtime.NamedReader("cert.pem", strings.NewReader(v.(string))))
		}
		if v, ok := d.GetOk("tls_key"); ok && v.(string) != "" {
			params.SetTLSKeyFile(runtime.NamedReader("key.pem", strings.NewReader(v.(string))))
		}
	}

	ctx, errBody := withErrorCapture(ctx)
	params.SetContext(ctx)
	resp, err := client.Client.Endpoints.EndpointCreate(params, client.AuthInfo)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create environment: %w", decorateSDKError(err, errBody)))
	}

	d.SetId(strconv.FormatInt(resp.Payload.ID, 10))

	fields := map[string]interface{}{}
	if resp.Payload.EdgeKey != "" {
		fields["edge_key"] = resp.Payload.EdgeKey
	}
	if resp.Payload.EdgeID != "" {
		fields["edge_id"] = resp.Payload.EdgeID
	}
	if err := setFields(d, fields); err != nil {
		return diag.FromErr(err)
	}

	// For edge agents, tags and the public URL are not honoured by the
	// multipart Create request and must be applied via a follow-up Update.
	if isEdgeAgent {
		_, hasTags := d.GetOk("tag_ids")
		publicIP, hasPublicIP := d.GetOk("public_ip")
		if hasTags || (hasPublicIP && publicIP.(string) != "") {
			if diags := resourceEnvironmentUpdate(ctx, d, meta); diags.HasError() {
				return diags
			}
		}
	}

	if _, ok := d.GetOk("user_access_policies"); ok {
		if diags := resourceEnvironmentUpdate(ctx, d, meta); diags.HasError() {
			return diags
		}
	}
	if _, ok := d.GetOk("team_access_policies"); ok {
		if diags := resourceEnvironmentUpdate(ctx, d, meta); diags.HasError() {
			return diags
		}
	}

	if diags := resourceEnvironmentRead(ctx, d, meta); diags.HasError() {
		return diags
	}
	return diag.FromErr(ensureEdgeID(d))
}

// trimURLScheme strips a leading http:// or https:// from an environment
// address so values can be compared the way Portainer stores them for Edge
// Agents (scheme-less host).
func trimURLScheme(s string) string {
	for _, scheme := range []string{"https://", "http://"} {
		if trimmed, ok := strings.CutPrefix(s, scheme); ok {
			return trimmed
		}
	}
	return s
}

// edgeAddressFromKey recovers the Portainer address an Edge Agent environment
// was created with. Portainer stores endpoint.URL for edge types as a bare host
// (edge.ParseHostForEdge drops the scheme, the port and the path), but the edge
// key keeps the submitted URL verbatim in its first field:
//
//	base64("<portainer url>|<tunnel host:port>|<tls fingerprint>|<endpoint id>")
//
// so the key - not endpoint.URL - is the lossless source for
// environment_address. Returns "" when the key is absent or not in that shape,
// which leaves the caller on its endpoint.URL fallback.
func edgeAddressFromKey(edgeKey string) string {
	if edgeKey == "" {
		return ""
	}
	decoded, err := base64.StdEncoding.DecodeString(edgeKey)
	if err != nil {
		// Portainer emits the key unpadded (base64.RawStdEncoding).
		decoded, err = base64.RawStdEncoding.DecodeString(edgeKey)
		if err != nil {
			return ""
		}
	}
	fields := strings.Split(string(decoded), "|")
	if len(fields) != 4 {
		return ""
	}
	return strings.TrimSpace(fields[0])
}

func findExistingEnvironmentByName(client *APIClient, name string) (int, error) {
	ctx, errBody := withErrorCapture(context.Background())
	params := endpoints.NewEndpointListParams()
	params.SetContext(ctx)
	resp, err := client.Client.Endpoints.EndpointList(params, client.AuthInfo)
	if err != nil {
		return 0, fmt.Errorf("failed to list environments: %w", decorateSDKError(err, errBody))
	}

	for _, e := range resp.Payload {
		if e.Name == name {
			return int(e.ID), nil
		}
	}
	return 0, nil
}

func resourceEnvironmentRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*APIClient)
	id, _ := strconv.ParseInt(d.Id(), 10, 64)

	ctx, errBody := withErrorCapture(ctx)
	params := endpoints.NewEndpointInspectParams()
	params.SetContext(ctx)
	params.ID = id

	resp, err := client.Client.Endpoints.EndpointInspect(params, client.AuthInfo)
	if err != nil {
		var notFound *endpoints.EndpointInspectNotFound
		if errors.As(err, &notFound) {
			d.SetId("")
			return nil
		}
		return diag.FromErr(fmt.Errorf("failed to read environment: %w", decorateSDKError(err, errBody)))
	}

	if err := d.Set("name", resp.Payload.Name); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("type", int(resp.Payload.Type)); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("group_id", int(resp.Payload.GroupID)); err != nil {
		return diag.FromErr(err)
	}
	envType := int(resp.Payload.Type)
	// Until an agent associates, Portainer reports an empty EdgeID (unless the
	// EnforceEdgeID setting is enabled), so for Edge Agent environments keep the
	// ID generated at create time rather than wiping it (issue #142). A
	// server-reported ID always wins, and non-edge environments keep reflecting
	// the API verbatim.
	edgeID := resp.Payload.EdgeID
	if edgeID == "" && (envType == 4 || envType == 7) {
		edgeID = d.Get("edge_id").(string)
	}
	if err := d.Set("edge_id", edgeID); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("edge_key", resp.Payload.EdgeKey); err != nil {
		return diag.FromErr(err)
	}
	// Portainer stores the Edge Agent URL as a bare host, so a configured
	// "https://portainer.example.com" comes back as "portainer.example.com" and
	// "http://portainer:9000" comes back as "portainer" - both show up as
	// perpetual drift (issue #136). The edge key still carries the address
	// verbatim, so prefer it and fall back to the endpoint URL only when the key
	// is missing or unparsable, keeping the scheme already in state in that
	// case. A genuine address change stays visible: it is baked into the key at
	// create time and needs the environment to be replaced.
	address := resp.Payload.URL
	if envType == 4 || envType == 7 {
		if fromKey := edgeAddressFromKey(resp.Payload.EdgeKey); fromKey != "" {
			address = fromKey
		} else if prior, ok := d.GetOk("environment_address"); ok {
			if s := prior.(string); s != address && trimURLScheme(s) == trimURLScheme(address) {
				address = s
			}
		}
	}
	if err := d.Set("environment_address", address); err != nil {
		return diag.FromErr(err)
	}

	if resp.Payload.PublicURL != "" {
		if err := d.Set("public_ip", resp.Payload.PublicURL); err != nil {
			return diag.FromErr(err)
		}
	} else {
		if err := d.Set("public_ip", ""); err != nil {
			return diag.FromErr(err)
		}
	}

	tagIDs := []int{}
	for _, tid := range resp.Payload.TagIds {
		tagIDs = append(tagIDs, int(tid))
	}
	if err := d.Set("tag_ids", tagIDs); err != nil {
		return diag.FromErr(err)
	}

	return nil
}

func resourceEnvironmentUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*APIClient)
	id, _ := strconv.ParseInt(d.Id(), 10, 64)

	ctx, errBody := withErrorCapture(ctx)
	params := endpoints.NewEndpointUpdateParams()
	params.SetContext(ctx)
	params.ID = id
	params.Body = &models.EndpointsEndpointUpdatePayload{}

	// Edge Agent environments (type 4, 7) trigger proxy/tunnel registration on
	// update when URL or TLS fields are included, which fails when the agent is
	// not yet connected. Only send metadata fields for edge agents.
	envType := d.Get("type").(int)
	isEdgeAgent := envType == 4 || envType == 7
	if !isEdgeAgent {
		params.Body.Name = d.Get("name").(string)
		params.Body.URL = d.Get("environment_address").(string)
		params.Body.GroupID = int64(d.Get("group_id").(int))
		params.Body.TLS = d.Get("tls_enabled").(bool)
		params.Body.TlsskipVerify = d.Get("tls_skip_verify").(bool)
		params.Body.TlsskipClientVerify = d.Get("tls_skip_client_verify").(bool)
	}

	if v, ok := d.GetOk("public_ip"); ok && v.(string) != "" {
		params.Body.PublicURL = v.(string)
	} else if !isEdgeAgent {
		// Portainer defaults the public URL to the connection URL for
		// directly-connected environments. Edge agents connect back to
		// Portainer, so environment_address is not a usable public URL there.
		params.Body.PublicURL = d.Get("environment_address").(string)
	}

	if v, ok := d.GetOk("tag_ids"); ok {
		tagIDs := make([]int64, 0, len(v.([]interface{})))
		for _, tid := range v.([]interface{}) {
			tagIDs = append(tagIDs, int64(tid.(int)))
		}
		params.Body.TagIDs = tagIDs
	}

	if v, ok := d.GetOk("user_access_policies"); ok {
		policies := make(models.PortainerUserAccessPolicies)
		for userID, role := range v.(map[string]interface{}) {
			policies[userID] = models.PortainerAccessPolicy{RoleID: int64(role.(int))}
		}
		params.Body.UserAccessPolicies = policies
	}

	if v, ok := d.GetOk("team_access_policies"); ok {
		policies := make(models.PortainerTeamAccessPolicies)
		for teamID, role := range v.(map[string]interface{}) {
			policies[teamID] = models.PortainerAccessPolicy{RoleID: int64(role.(int))}
		}
		params.Body.TeamAccessPolicies = policies
	}

	_, err := client.Client.Endpoints.EndpointUpdate(params, client.AuthInfo)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update environment: %w", decorateSDKError(err, errBody)))
	}

	diags := resourceEnvironmentRead(ctx, d, meta)
	if isEdgeAgent && d.HasChange("environment_address") {
		// The address is only ever sent at create time for edge agents (see
		// above), and Portainer generates the edge key from it right there, so
		// an edit cannot be applied in place. Say so instead of letting the
		// apply look successful.
		//
		// Only a change of host is worth warning about: a difference in the
		// scheme alone comes from Portainer's own host-only normalisation of
		// endpoint.URL (issue #136), not from an operator edit, and would
		// otherwise warn on every apply for environments still holding a
		// scheme-less address in state.
		old, new := d.GetChange("environment_address")
		if trimURLScheme(old.(string)) != trimURLScheme(new.(string)) {
			diags = append(diags, diag.Diagnostic{
				Severity: diag.Warning,
				Summary:  "environment_address was not applied to the Edge Agent environment",
				Detail: "Portainer bakes the address into the edge key when the environment is created and never regenerates it on update, so the running agent keeps using the previous address. " +
					"Replace the resource (terraform apply -replace=...) to get a new edge key, then redeploy the agent with it.",
			})
		}
	}
	return diags
}

func resourceEnvironmentDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*APIClient)
	id, _ := strconv.ParseInt(d.Id(), 10, 64)

	ctx, errBody := withErrorCapture(ctx)
	params := endpoints.NewEndpointDeleteParams()
	params.SetContext(ctx)
	params.ID = id

	_, err := client.Client.Endpoints.EndpointDelete(params, client.AuthInfo)
	if err != nil {
		var notFound *endpoints.EndpointDeleteNotFound
		if errors.As(err, &notFound) {
			return nil
		}
		return diag.FromErr(fmt.Errorf("failed to delete environment: %w", decorateSDKError(err, errBody)))
	}

	return nil
}
