package internal

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
)

// The Portainer Go SDK (client-api-go) is generated by go-swagger. Its error
// response readers (e.g. EndpointCreateBadRequest.readResponse) have empty
// bodies that discard the actual response payload from Portainer, leaving the
// caller with placeholder strings like "[POST /endpoints][400]
// endpointCreateBadRequest" with no detail about what Portainer rejected.
//
// errorCaptureTransport wraps the HTTP transport used by the SDK and, on any
// non-2xx response, snapshots the response body into a request-scoped
// *capturedErrorBody before re-injecting the bytes so downstream readers still
// see the original body. Call sites that talk to the SDK pair their call with
// withErrorCapture() + decorateSDKError() to surface the real payload.

type errorBodyKey struct{}

type capturedErrorBody struct {
	Status int
	Body   []byte
}

func withErrorCapture(ctx context.Context) (context.Context, *capturedErrorBody) {
	c := &capturedErrorBody{}
	return context.WithValue(ctx, errorBodyKey{}, c), c
}

type errorCaptureTransport struct {
	next http.RoundTripper
}

func (t *errorCaptureTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	resp, err := t.next.RoundTrip(req)
	if err != nil || resp == nil || resp.StatusCode < 400 {
		return resp, err
	}
	capture, ok := req.Context().Value(errorBodyKey{}).(*capturedErrorBody)
	if !ok {
		return resp, nil
	}
	body, readErr := io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	if readErr != nil {
		return resp, nil
	}
	capture.Status = resp.StatusCode
	capture.Body = body
	resp.Body = io.NopCloser(bytes.NewReader(body))
	return resp, nil
}

func decorateSDKError(err error, capture *capturedErrorBody) error {
	if err == nil || capture == nil || len(capture.Body) == 0 {
		return err
	}
	return fmt.Errorf("%w: %s", err, bytes.TrimSpace(capture.Body))
}
