name: Terraform CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Show Terraform version
        run: terraform version

      - name: Initialize Terraform
        run: make init

      - name: Validate Terraform configuration
        run: make validate

      - name: Check Terraform formatting
        run: make fmt-check
